// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6g7ynAlC2FfqqCZGiaQ0uW2zBQWB65ew',
    appId: '1:445307256775:web:c745a28229b088d0caa3e2',
    messagingSenderId: '445307256775',
    projectId: 'tiendaapp-f4bd1',
    authDomain: 'tiendaapp-f4bd1.firebaseapp.com',
    storageBucket: 'tiendaapp-f4bd1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp_8HzABulfaYBTPIbpt5Ye4GGhKXdB0I',
    appId: '1:445307256775:android:0ca9fdff317f31dfcaa3e2',
    messagingSenderId: '445307256775',
    projectId: 'tiendaapp-f4bd1',
    storageBucket: 'tiendaapp-f4bd1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7-F0DqBTSqg6E7YHvyi0m8UwmK8Bmjkk',
    appId: '1:445307256775:ios:326fe773836fd196caa3e2',
    messagingSenderId: '445307256775',
    projectId: 'tiendaapp-f4bd1',
    storageBucket: 'tiendaapp-f4bd1.firebasestorage.app',
    iosBundleId: 'com.example.tiendaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7-F0DqBTSqg6E7YHvyi0m8UwmK8Bmjkk',
    appId: '1:445307256775:ios:326fe773836fd196caa3e2',
    messagingSenderId: '445307256775',
    projectId: 'tiendaapp-f4bd1',
    storageBucket: 'tiendaapp-f4bd1.firebasestorage.app',
    iosBundleId: 'com.example.tiendaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6g7ynAlC2FfqqCZGiaQ0uW2zBQWB65ew',
    appId: '1:445307256775:web:17b2e635a47b931bcaa3e2',
    messagingSenderId: '445307256775',
    projectId: 'tiendaapp-f4bd1',
    authDomain: 'tiendaapp-f4bd1.firebaseapp.com',
    storageBucket: 'tiendaapp-f4bd1.firebasestorage.app',
  );
}
